### ISSUE TITLE
Argument of type 'Repository<ProductReview>' is not assignable to parameter of type 'Repository<any> & Repository<ProductReview 

### ISSUE THREAD

**Issue by alyrna** [pevey/medusa-plugin-ratings#1]
While building the project I am getting errors regarding the product review services. 

```const productReviewRepository = this.activeManager_.withRepository(this.productReviewRepository_)
                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/product-review.ts:23:72 - error TS2345: Argument of type 'Repository<ProductReview>' is not assignable to parameter of type 'Repository<any> & Repository<ProductReview | { product_id?: string; product?: DeepPartial<Product>; customer_id?: string; customer?: DeepPartial<Customer>; ... 6 more ...; updated_at?: DeepPartial<...>; }>'.
```

every line which this.productReviewRepository_ is used in the file src/services/product-review.ts is throwing this error

**Comment by pevey** [comment]
If you are building yourself, are you familiar with the build procedures for medusa plugins?  You have to yarn link the peer dependencies.  

If you need to make customizations, you will probably find it easier to copy the code from src into your medusa project src folder rather than rebuilding the plugin.

If you don't need to make customizations, just install it from npm rather than trying to build it.
